"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  useAgentStore, useUIStore, useCityDataStore, useSimulationStore,
  AGENTS, AgentId, AgentMessage,
} from '@/stores';
import { Bot, Send, X, Brain, Activity, MapPin, AlertTriangle, Zap, Target, ArrowRight, Clock, Loader2, Building2, Leaf } from 'lucide-react';

const AGENT_ICONS: Record<AgentId, React.ReactNode> = {
  executive: <Target size={16} />,
  urban: <Building2 size={16} />,
  disaster: <AlertTriangle size={16} />,
  sustainability: <Leaf size={16} />,
  infrastructure: <Zap size={16} />,
};

const AGENT_LUCIDE_ICONS: Record<AgentId, React.ReactNode> = {
  executive: <Target size={32} strokeWidth={1.5} />,
  urban: <Building2 size={32} strokeWidth={1.5} />,
  disaster: <AlertTriangle size={32} strokeWidth={1.5} />,
  sustainability: <Leaf size={32} strokeWidth={1.5} />,
  infrastructure: <Zap size={32} strokeWidth={1.5} />,
};

const AGENT_RESPONSES: Record<AgentId, Record<string, string>> = {
  executive: {
    default: "Based on current city metrics — City Health 64/100, Congestion 67%, AQI 142 — I recommend three immediate priorities:\n\n**1. Metro Corridor Acceleration** — Electronic City to Hebbal line has the highest ROI based on traffic density modeling. Impact: −12% congestion on Outer Ring Road.\n\n**2. Eastern Substation Reinforcement** — Substations #7 and #11 are at 91% and 87% capacity. Risk of cascading failure by Q3 2027 if not addressed.\n\n**3. Water Infrastructure NE Corridor** — Demand-supply gap of 350 MLD projected by 2027 in Whitefield-Marathahalli belt.\n\nShall I generate a board-ready briefing on any of these?",
    briefing: "**BENGALURU URBAN INTELLIGENCE — QUARTERLY BRIEFING**\n\nCity Health Score: **64/100** (Moderate)\n\nKey Findings:\n• Traffic congestion at 67% — up 4% vs Q3\n• AQI at 142 — Moderate category, improving\n• Grid load at 4.1 GW — stable, headroom adequate\n• Water stress index: 1.24 — above sustainable threshold\n\nRecommended Actions:\n1. Expedite Metro Line 4 tender (saves ₹340 Cr in road maintenance)\n2. Approve 50 EV charging stations in Electronic City\n3. Emergency water audit — Bellandur catchment zone\n\n*Generated by Bhavora Urban Intelligence OS — confidence 87%*",
  },
  urban: {
    default: "For metro corridor optimization, the Hebbal–Whitefield alignment shows the highest population-weighted demand. Based on gravity model analysis:\n\n**Priority Corridors:**\n1. Hebbal → Whitefield (demand: 285k pax/day)\n2. Sarjapur Road extension (demand: 198k pax/day)\n3. Outer Ring Road phase 3 (demand: 176k pax/day)\n\nHigh-density residential development is most viable in:\n- Sarjapur Road (FSI 4.0 permissible)\n- Thanisandra Main Road (transit-oriented zone)\n- Yelahanka New Town (metro station proximity)\n\nShould I run a full zoning analysis for any of these areas?",
    density: "Whitefield faces a density problem: 18,000 persons/km² with inadequate trunk infrastructure. Recommended interventions:\n\n**Immediate:** \n• Enforce parking caps to discourage private vehicle use\n• Prioritize BMTC feeder routes to existing metro at Kadugodi\n\n**Medium-term:**\n• Widen Hope Farm Junction — single point causing 34% area congestion\n• Commercial-residential mixed-use permitted along 150m of Whitefield Main Road\n\n**Long-term:**\n• Phase 2 purple line extension adds 4 new stations in zone\n• Expected impact: −22% peak congestion, +18% property value",
  },
  disaster: {
    default: "Monsoon flood risk analysis for Bengaluru 2025:\n\n**High Risk Zones (100-year flood):**\n🔴 Bellandur Lake periphery — 3,200 households at risk\n🔴 Varthur catchment — 1,800 structures in flood plain\n🔴 Koramangala valley — Storm drain capacity exceeded at >85mm/hr\n\n**Medium Risk:**\n🟡 Hebbal valley — overflow risk above 95mm/24hr\n🟡 Rachenahalli Lake area — bund maintenance overdue\n\n**Recommended pre-monsoon actions:**\n1. Desilting — 23 storm drains require emergency desilting\n2. Pump station readiness audit — 8 stations not operational\n3. Early warning sensors — install 12 sensors in high-risk zones\n\nShall I generate an evacuation plan for any specific zone?",
    evacuation: "**EVACUATION PLAN — ELECTRONIC CITY**\n\nTrigger: Grid failure or flash flood event\n\nPrimary Routes:\n→ Electronic City Phase 1: Hosur Road to NICE Road (capacity 18,000 veh/hr)\n→ Electronic City Phase 2: Neeladri Road to Bommasandra (capacity 12,000 veh/hr)\n\nAssembly Points:\n• Bommasandra Ground — capacity 8,000 persons\n• Hebbagodi School — capacity 3,500 persons\n\nTimeline:\n• T+0: Alert activated\n• T+15min: Traffic police deployed at 6 junctions\n• T+30min: BMTC emergency buses dispatched (14 buses)\n• T+2hr: Target 80% evacuation complete\n\nEstimated affected population: 47,000 in Zone 4",
  },
  sustainability: {
    default: "Carbon neutrality pathway for Bengaluru by 2040:\n\n**Current State:** 42,000 kt CO₂/yr\n**2040 Target:** Net Zero\n\n**Pathway:**\n2025-2028: EV fleet transition (−8% transport CO₂)\n2028-2032: 60% renewable grid (−18% energy CO₂)\n2032-2036: Green building codes (−6% building CO₂)\n2036-2040: Industrial efficiency + carbon sequestration\n\n**Key Lever — Carbon by Sector:**\n• Transport: 43% → target 15% by 2040 (EV + Metro)\n• Energy: 39% → target 5% (renewables)\n• Industry: 18% → target 8% (efficiency standards)\n\nWater stress outlook: 1.24 → projected 1.68 by 2030 without intervention. Priority: upgrade Cauvery Stage 5 supply.",
    water: "Water stress forecast for Bengaluru 2025-2030:\n\n**Current:** Demand 1,800 MLD | Supply 1,450 MLD | Gap: 350 MLD\n\n**2027 Projection:**\n• Demand: 2,050 MLD (+14%)\n• Supply: 1,580 MLD (Stage 5 upgrade)\n• Gap: **470 MLD** (critical)\n\n**District Risk Map:**\n🔴 Whitefield: 62% groundwater dependent, depletion rate 3m/yr\n🔴 Electronic City: 78% tanker dependent during peak\n🟡 Koramangala: Aging network, 40% distribution loss\n🟢 Indiranagar: Cauvery supply reliable\n\n**Priority Actions:**\n1. Accelerate Cauvery Stage 5 (adds 775 MLD by 2026)\n2. 150 rainwater harvesting mandatory structures in Whitefield\n3. 40% distribution loss reduction program (saves 300 MLD/yr)",
  },
  infrastructure: {
    default: "Power grid risk assessment — Bengaluru 2025:\n\n**Substations at Risk:**\n🔴 Substation #7 (Whitefield) — 91% capacity, maintenance overdue 8 months\n🔴 Substation #11 (Electronic City) — 87% capacity, aging transformers\n🟡 Substation #23 (Hebbal) — 74% capacity, growth trajectory concerning\n🟡 Substation #31 (Sarjapur) — 71% capacity, new residential adds load\n\n**Recommended EV Station Locations (next 50):**\nTop priority: Whitefield, Koramangala, Indiranagar (high EV adoption + low density coverage)\nSecondary: Hebbal, Jayanagar, JP Nagar\n\n**Maintenance Priority Order:**\n1. Sub #7 — emergency transformer replacement (Q2 2025)\n2. Sub #11 — load balancing + new feeder (Q3 2025)\n3. Road network: Outer Ring Road 4-lane → 6-lane from Marathahalli to KR Puram",
    ev: "**EV Charging Station Placement Analysis**\n\nOptimal 50 locations based on:\n• Population density\n• Vehicle registration data\n• Existing coverage gaps\n• Grid capacity availability\n\n**Zone A — Whitefield (12 stations)**\nHope Farm Junction × 3, Whitefield Main Road × 4, ITPL × 3, VGP Garden × 2\nGrid feeder: Whitefield 66kV substation (available capacity: 8 MW)\n\n**Zone B — Electronic City (10 stations)**\nPhase 1 × 5, Phase 2 × 3, Bommasandra × 2\nGrid feeder: Hebbagodi 66kV (available: 6.5 MW)\n\n**Zone C — Koramangala (8 stations)**\n1st–8th Block distribution, Sony World signal area\n\nTotal estimated cost: ₹24 Cr\nPayback period: 6.2 years at current utilization rates",
  },
};

function getAgentResponse(agentId: AgentId, userMessage: string): string {
  const lowerMsg = userMessage.toLowerCase();
  const responses = AGENT_RESPONSES[agentId];

  if (agentId === 'executive') {
    if (lowerMsg.includes('brief') || lowerMsg.includes('summary') || lowerMsg.includes('report')) return responses.briefing;
    return responses.default;
  }
  if (agentId === 'urban') {
    if (lowerMsg.includes('density') || lowerMsg.includes('whitefield')) return responses.density;
    return responses.default;
  }
  if (agentId === 'disaster') {
    if (lowerMsg.includes('evacuat') || lowerMsg.includes('electronic city')) return responses.evacuation;
    return responses.default;
  }
  if (agentId === 'sustainability') {
    if (lowerMsg.includes('water') || lowerMsg.includes('stress')) return responses.water;
    return responses.default;
  }
  if (agentId === 'infrastructure') {
    if (lowerMsg.includes('ev') || lowerMsg.includes('charging')) return responses.ev;
    return responses.default;
  }
  return responses.default;
}

function getActionCards(agentId: AgentId, text: string): { label: string; path: string }[] {
  const actions: { label: string; path: string }[] = [];
  if (text.includes('Metro') || text.includes('corridor')) {
    actions.push({ label: 'View Metro Map', path: '/cities' });
    actions.push({ label: 'Run Metro Simulation', path: '/simulate' });
  }
  if (text.includes('Substation') || text.includes('grid') || text.includes('power')) {
    actions.push({ label: 'View Grid Status', path: '/disaster' });
    actions.push({ label: 'Run Grid Simulation', path: '/simulate' });
  }
  if (text.includes('flood') || text.includes('evacuat') || text.includes('risk zone')) {
    actions.push({ label: 'View Flood Map', path: '/disaster' });
    actions.push({ label: 'Run Disaster Simulation', path: '/simulate' });
  }
  if (text.includes('EV') || text.includes('charging')) {
    actions.push({ label: 'View EV Map', path: '/overview' });
    actions.push({ label: 'Run EV Simulation', path: '/simulate' });
  }
  if (text.includes('Carbon') || text.includes('water stress') || text.includes('sustainability')) {
    actions.push({ label: 'View Sustainability Dashboard', path: '/cities' });
  }
  if (text.includes('density') || text.includes('zoning')) {
    actions.push({ label: 'View Zoning Map', path: '/overview' });
  }
  if (text.includes('Briefing') || text.includes('QUARTERLY')) {
    actions.push({ label: 'Generate Full Report', path: '/simulate' });
  }
  return actions.slice(0, 3);
}

function getAgentGreeting(agentId: AgentId, cityData: { metrics: { cityHealthScore: number; congestionIndex: number; aqi: number; activeIncidents: number; gridLoad: number; waterDemand: number } }): string {
  const { cityHealthScore, congestionIndex, aqi, activeIncidents, gridLoad, waterDemand } = cityData.metrics;
  const greetings: Record<AgentId, string> = {
    executive: `City Health ${cityHealthScore}/100 · Congestion ${congestionIndex}% · AQI ${aqi} · ${activeIncidents} active incidents`,
    urban: `Current density load: ${congestionIndex}% congestion · ${waterDemand} MLD demand · Ready for zoning analysis`,
    disaster: `${activeIncidents} active incidents · AQI ${aqi} · Flood risk monitoring active for monsoon season`,
    sustainability: `Carbon trajectory tracking · Water gap ${1800 - waterDemand} MLD · Grid load ${gridLoad} GW`,
    infrastructure: `Grid at ${gridLoad} GW · ${activeIncidents} infrastructure alerts · EV adoption analysis ready`,
  };
  return greetings[agentId] || 'System nominal';
}

function FormatResponse({ text }: { text: string }) {
  const lines = text.split('\n');
  return (
    <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.8)', lineHeight: 1.7 }}>
      {lines.map((line, i) => {
        const trimmed = line.trim();
        if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
          return <div key={i} style={{ fontWeight: 700, color: '#fff', marginTop: i > 0 ? '12px' : 0, marginBottom: '4px', fontSize: '14px' }}>{trimmed.replace(/\*\*/g, '')}</div>;
        }
        if (trimmed.startsWith('• ') || trimmed.startsWith('→ ') || trimmed.startsWith('- ')) {
          const prefix = trimmed.startsWith('→ ') ? '→' : '•';
          const content = trimmed.replace(/^[•→\-]\s*/, '');
          const emojiMatch = content.match(/^([🔴🟡🟢])/);
          if (emojiMatch) {
            return (
              <div key={i} style={{ paddingLeft: '12px', display: 'flex', alignItems: 'flex-start', gap: '6px', color: 'rgba(255,255,255,0.7)' }}>
                <span>{emojiMatch[1]}</span>
                <span>{content.slice(emojiMatch[1].length).trim()}</span>
              </div>
            );
          }
          return (
            <div key={i} style={{ paddingLeft: '12px', display: 'flex', alignItems: 'flex-start', gap: '6px', color: 'rgba(255,255,255,0.7)' }}>
              <span style={{ color: 'rgba(255,255,255,0.4)' }}>{prefix}</span>
              <span>{content}</span>
            </div>
          );
        }
        if (trimmed.match(/^\d+\./)) {
          const [num, ...rest] = trimmed.split('. ');
          return (
            <div key={i} style={{ paddingLeft: '12px', display: 'flex', alignItems: 'flex-start', gap: '8px', marginTop: '6px' }}>
              <span style={{
                width: '20px',
                height: '20px',
                borderRadius: '50%',
                background: 'rgba(0,212,255,0.15)',
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '10px',
                fontWeight: 700,
                color: '#00D4FF',
                flexShrink: 0,
              }}>{num}</span>
              <span style={{ color: 'rgba(255,255,255,0.7)' }}>{rest.join('. ')}</span>
            </div>
          );
        }
        if (trimmed.includes('🔴') || trimmed.includes('🟡') || trimmed.includes('🟢')) {
          const emoji = trimmed.match(/[🔴🟡🟢]/)?.[0] || '';
          const rest = trimmed.replace(/[🔴🟡🟢]/, '').trim();
          const colors: Record<string, string> = { '🔴': '#EF4444', '🟡': '#F59E0B', '🟢': '#10B981' };
          return (
            <div key={i} style={{ paddingLeft: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: colors[emoji] || 'rgba(255,255,255,0.4)', flexShrink: 0 }} />
              <span>{rest}</span>
            </div>
          );
        }
        if (trimmed.startsWith('*') && trimmed.endsWith('*')) {
          return <div key={i} style={{ fontSize: '11px', color: 'rgba(255,255,255,0.35)', fontStyle: 'italic', marginTop: '8px' }}>{trimmed.replace(/\*/g, '')}</div>;
        }
        if (trimmed.startsWith('```')) {
          const codeContent: string[] = [];
          let j = i + 1;
          while (j < lines.length && !lines[j].trim().startsWith('```')) {
            codeContent.push(lines[j]);
            j++;
          }
          return (
            <div key={i} style={{
              background: 'rgba(0,0,0,0.3)',
              border: '1px solid rgba(255,255,255,0.08)',
              borderRadius: '6px',
              padding: '10px',
              fontFamily: 'var(--font-jetbrains, monospace)',
              fontSize: '12px',
              color: 'rgba(255,255,255,0.7)',
              whiteSpace: 'pre-wrap',
              marginTop: '8px',
              marginBottom: '8px',
            }}>
              {codeContent.join('\n')}
            </div>
          );
        }
        if (trimmed.includes('|') && trimmed.includes('—')) {
          const parts = trimmed.split(/[—–-]/).map(s => s.trim());
          if (parts.length >= 2) {
            return (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '2px 0', fontSize: '12px', color: 'rgba(255,255,255,0.6)' }}>
                <span>{parts[0]}</span>
                <span style={{ color: 'rgba(255,255,255,0.8)', fontFamily: 'var(--font-jetbrains, monospace)' }}>{parts.slice(1).join(' — ')}</span>
              </div>
            );
          }
        }
        if (line === '') return <div key={i} style={{ height: '6px' }} />;
        return <div key={i}>{line}</div>;
      })}
    </div>
  );
}

export function AgentHub() {
  const { isAgentHubOpen, activeAgentId, openAgentHub, closeAgentHub } = useUIStore();
  const { conversations, addMessage, clearConversation, isLoading, setLoading } = useAgentStore();
  const cityData = useCityDataStore();
  const sim = useSimulationStore();

  const [input, setInput] = useState('');
  const messagesEndRef = React.useRef<HTMLDivElement>(null);

  const agentId = activeAgentId as AgentId;
  const agent = AGENTS[agentId];
  const messages = conversations[agentId] || [];

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;
    const userMsg: AgentMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content: input.trim(),
      timestamp: new Date(),
    };
    addMessage(agentId, userMsg);
    setInput('');
    setLoading(true);

    await new Promise(r => setTimeout(r, 1200 + Math.random() * 800));

    const responseText = getAgentResponse(agentId, userMsg.content);
    const actions = getActionCards(agentId, responseText);
    const agentMsg: AgentMessage = {
      id: `msg-${Date.now() + 1}`,
      role: 'agent',
      content: responseText,
      timestamp: new Date(),
      actions: actions.length > 0 ? actions : undefined,
    };
    addMessage(agentId, agentMsg);
    setLoading(false);
  };

  const statusColor = isLoading ? '#F59E0B' : '#10B981';
  const statusLabel = isLoading ? 'Thinking...' : 'Online';

  return (
    <>
      <motion.button
        whileHover={{ scale: 1.08 }}
        whileTap={{ scale: 0.92 }}
        onClick={() => isAgentHubOpen ? closeAgentHub() : openAgentHub()}
        style={{
          position: 'fixed',
          bottom: '24px',
          right: '24px',
          width: '56px',
          height: '56px',
          borderRadius: '50%',
          background: 'linear-gradient(135deg, #00D4FF, #7C3AED)',
          border: 'none',
          cursor: 'pointer',
          zIndex: 9990,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          boxShadow: '0 4px 24px rgba(0,212,255,0.35), 0 8px 40px rgba(124,58,237,0.2)',
        }}
        title="AI Agent Hub (Ctrl+/)"
        aria-label="Open AI Agent Hub"
      >
        <Bot size={24} color="white" />
      </motion.button>

      <AnimatePresence>
        {isAgentHubOpen && (
          <motion.div
            initial={{ opacity: 0, y: 24, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 16, scale: 0.95 }}
            transition={{ type: 'spring', damping: 26, stiffness: 300 }}
            style={{
              position: 'fixed',
              right: '24px',
              bottom: '96px',
              width: '440px',
              maxHeight: '78vh',
              background: 'linear-gradient(170deg, var(--bg-surface-1) 0%, color-mix(in srgb, var(--bg-surface-1) 95%, #000) 100%)',
              border: '1px solid rgba(255,255,255,0.06)',
              borderRadius: '16px',
              boxShadow: '0 16px 48px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)',
              zIndex: 9989,
              display: 'flex',
              flexDirection: 'column',
              overflow: 'hidden',
            }}
          >
            {/* Header */}
            <div style={{
              padding: '14px 16px',
              borderBottom: '1px solid rgba(255,255,255,0.06)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              background: 'rgba(0,0,0,0.15)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{
                  width: '34px',
                  height: '34px',
                  borderRadius: '10px',
                  background: 'linear-gradient(135deg, rgba(0,212,255,0.2), rgba(124,58,237,0.2))',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: '1px solid rgba(0,212,255,0.15)',
                }}>
                  <Brain size={18} color="#00D4FF" />
                </div>
                <div>
                  <div style={{ fontSize: '13px', fontWeight: 700, color: '#fff', letterSpacing: '0.02em' }}>Bhavora Command</div>
                  <div style={{ fontSize: '10px', color: 'rgba(0,212,255,0.7)', textTransform: 'uppercase', letterSpacing: '0.08em', fontWeight: 600 }}>Intelligence Agent Hub</div>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '5px', fontSize: '10px', color: 'rgba(255,255,255,0.4)' }}>
                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: statusColor, boxShadow: `0 0 6px ${statusColor}` }} />
                  {statusLabel}
                </div>
                <motion.button
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                  onClick={closeAgentHub}
                  style={{ background: 'rgba(255,255,255,0.06)', border: 'none', color: 'rgba(255,255,255,0.5)', cursor: 'pointer', fontSize: '18px', padding: '4px', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', width: '26px', height: '26px' }}
                >
                  <X size={14} />
                </motion.button>
              </div>
            </div>

            {/* Agent Selector */}
            <div style={{
              display: 'flex',
              gap: '4px',
              padding: '10px 12px',
              borderBottom: '1px solid rgba(255,255,255,0.06)',
              overflowX: 'auto',
              background: 'rgba(0,0,0,0.08)',
            }}>
              {(Object.values(AGENTS) as typeof AGENTS[AgentId][]).map(a => {
                const isActive = activeAgentId === a.id;
                return (
                  <motion.button
                    key={a.id}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => openAgentHub(a.id)}
                    style={{
                      position: 'relative',
                      padding: '7px 12px 7px 10px',
                      borderRadius: '8px',
                      border: `1px solid ${isActive ? a.color : 'rgba(255,255,255,0.08)'}`,
                      background: isActive ? `${a.color}15` : 'transparent',
                      color: isActive ? a.color : 'rgba(255,255,255,0.5)',
                      fontSize: '11px',
                      fontWeight: 600,
                      cursor: 'pointer',
                      whiteSpace: 'nowrap',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px',
                      transition: 'all 120ms',
                    }}
                  >
                    <span style={{ fontSize: '14px' }}>{a.icon}</span>
                    <span>{a.name.split(' ')[0]}</span>
                    {isActive && (
                      <motion.div
                        layoutId="agent-indicator"
                        style={{
                          position: 'absolute',
                          bottom: '-1px',
                          left: '20%',
                          right: '20%',
                          height: '2px',
                          borderRadius: '1px',
                          background: a.color,
                        }}
                      />
                    )}
                    {isActive && (
                      <span style={{
                        width: '5px',
                        height: '5px',
                        borderRadius: '50%',
                        background: statusColor,
                        boxShadow: `0 0 4px ${statusColor}`,
                        flexShrink: 0,
                      }} />
                    )}
                  </motion.button>
                );
              })}
            </div>

            {/* System Status Strip */}
            <div style={{
              padding: '8px 14px',
              background: 'rgba(0,0,0,0.2)',
              borderBottom: '1px solid rgba(255,255,255,0.06)',
            }}>
              <div style={{ display: 'flex', gap: '14px', flexWrap: 'wrap', alignItems: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: cityData.metrics.cityHealthScore > 60 ? '#10B981' : '#EF4444', flexShrink: 0 }} />
                  <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.4)', fontWeight: 600 }}>HEALTH</span>
                  <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.8)', fontFamily: 'var(--font-jetbrains, monospace)', fontWeight: 700 }}>{cityData.metrics.cityHealthScore}</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <Activity size={10} color="rgba(255,255,255,0.4)" />
                  <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.4)', fontWeight: 600 }}>TRAFFIC</span>
                  <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.8)', fontFamily: 'var(--font-jetbrains, monospace)', fontWeight: 700 }}>{cityData.metrics.congestionIndex}%</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <AlertTriangle size={10} color={cityData.metrics.aqi > 150 ? '#EF4444' : 'rgba(255,255,255,0.4)'} />
                  <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.4)', fontWeight: 600 }}>AQI</span>
                  <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.8)', fontFamily: 'var(--font-jetbrains, monospace)', fontWeight: 700 }}>{cityData.metrics.aqi}</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <Zap size={10} color="rgba(255,255,255,0.4)" />
                  <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.4)', fontWeight: 600 }}>GRID</span>
                  <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.8)', fontFamily: 'var(--font-jetbrains, monospace)', fontWeight: 700 }}>{cityData.metrics.gridLoad}GW</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <MapPin size={10} color="rgba(255,255,255,0.4)" />
                  <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.4)', fontWeight: 600 }}>INCIDENTS</span>
                  <span style={{ fontSize: '11px', color: cityData.metrics.activeIncidents > 0 ? '#F59E0B' : 'rgba(255,255,255,0.8)', fontFamily: 'var(--font-jetbrains, monospace)', fontWeight: 700 }}>{cityData.metrics.activeIncidents}</span>
                </div>
              </div>
            </div>

            {/* Context Awareness Greeting Strip */}
            <div style={{
              padding: '6px 14px',
              background: 'rgba(0,212,255,0.04)',
              borderBottom: '1px solid rgba(255,255,255,0.06)',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
            }}>
              <Brain size={10} color="rgba(0,212,255,0.5)" />
              <span style={{ fontSize: '10px', color: 'rgba(0,212,255,0.6)', fontWeight: 500, fontFamily: 'var(--font-jetbrains, monospace)' }}>
                {getAgentGreeting(agentId, cityData)}
              </span>
            </div>

            {/* Quick Actions */}
            <div style={{ padding: '8px 12px', display: 'flex', gap: '5px', flexWrap: 'wrap', borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(0,0,0,0.05)' }}>
              {agent.quickActions.slice(0, 4).map(action => (
                <motion.button
                  key={action}
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => setInput(action)}
                  style={{
                    padding: '5px 12px',
                    borderRadius: '20px',
                    background: 'rgba(255,255,255,0.04)',
                    border: '1px solid rgba(255,255,255,0.08)',
                    color: 'rgba(255,255,255,0.55)',
                    fontSize: '10px',
                    fontWeight: 500,
                    cursor: 'pointer',
                    transition: 'all 120ms',
                    letterSpacing: '0.02em',
                  }}
                >
                  {action}
                </motion.button>
              ))}
              {agent.quickActions.length > 4 && (
                <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.25)', alignSelf: 'center' }}>+{agent.quickActions.length - 4} more</span>
              )}
            </div>

            {/* Messages */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '14px', display: 'flex', flexDirection: 'column', gap: '12px', background: 'rgba(0,0,0,0.1)' }}>
              {messages.length === 0 && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  style={{ textAlign: 'center', padding: '28px 16px', color: 'rgba(255,255,255,0.4)', fontSize: '12px' }}
                >
                  <div style={{
                    width: '56px',
                    height: '56px',
                    borderRadius: '16px',
                    background: `${agent.color}12`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    margin: '0 auto 12px',
                    border: `1px solid ${agent.color}20`,
                  }}>
                    {AGENT_LUCIDE_ICONS[agentId]}
                  </div>
                  <div style={{ fontWeight: 700, color: 'rgba(255,255,255,0.7)', marginBottom: '4px', fontSize: '14px' }}>{agent.name}</div>
                  <div style={{ color: 'rgba(255,255,255,0.4)', marginBottom: '8px' }}>{agent.domain}</div>
                  <div style={{ color: 'rgba(255,255,255,0.3)', lineHeight: 1.6 }}>Ask me anything about {agent.domain.split('·')[0].trim().toLowerCase()}</div>
                  <div style={{ marginTop: '12px', display: 'flex', gap: '6px', justifyContent: 'center', flexWrap: 'wrap' }}>
                    {agent.quickActions.slice(0, 2).map(qa => (
                      <button
                        key={qa}
                        onClick={() => setInput(qa)}
                        style={{
                          padding: '4px 10px',
                          borderRadius: '12px',
                          background: `${agent.color}10`,
                          border: `1px solid ${agent.color}20`,
                          color: agent.color,
                          fontSize: '10px',
                          fontWeight: 600,
                          cursor: 'pointer',
                        }}
                      >
                        Ask: {qa}
                      </button>
                    ))}
                  </div>
                </motion.div>
              )}
              <AnimatePresence initial={false}>
                {messages.map(msg => (
                  <motion.div
                    key={msg.id}
                    initial={{ opacity: 0, y: 12, scale: 0.98 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    transition={{ duration: 0.2, ease: 'easeOut' }}
                    style={{
                      display: 'flex',
                      flexDirection: msg.role === 'user' ? 'row-reverse' : 'row',
                      gap: '10px',
                      alignItems: 'flex-start',
                    }}
                  >
                    {msg.role === 'agent' && (
                      <div style={{
                        width: '30px',
                        height: '30px',
                        borderRadius: '10px',
                        background: `${agent.color}15`,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        flexShrink: 0,
                        border: `1px solid ${agent.color}20`,
                        fontSize: '16px',
                      }}>
                        {agent.icon}
                      </div>
                    )}
                    <div style={{
                      maxWidth: '82%',
                      padding: msg.role === 'user' ? '10px 14px' : '12px 14px',
                      borderRadius: msg.role === 'user' ? '14px 14px 6px 14px' : '14px 14px 14px 6px',
                      background: msg.role === 'user'
                        ? 'linear-gradient(135deg, rgba(0,212,255,0.15), rgba(124,58,237,0.12))'
                        : 'rgba(255,255,255,0.03)',
                      border: msg.role === 'user'
                        ? '1px solid rgba(0,212,255,0.15)'
                        : '1px solid rgba(255,255,255,0.06)',
                      backdropFilter: msg.role === 'agent' ? 'blur(8px)' : 'none',
                      boxShadow: msg.role === 'agent' ? '0 2px 8px rgba(0,0,0,0.15)' : 'none',
                    }}>
                      {msg.role === 'agent' ? (
                        <FormatResponse text={msg.content} />
                      ) : (
                        <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.85)' }}>{msg.content}</div>
                      )}

                      {/* Action Cards */}
                      {msg.actions && msg.actions.length > 0 && (
                        <div style={{ marginTop: '12px', borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '10px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
                          <div style={{ fontSize: '9px', color: 'rgba(255,255,255,0.3)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '2px' }}>Quick Actions</div>
                          {msg.actions.map((action, idx) => (
                            <motion.button
                              key={idx}
                              whileHover={{ scale: 1.02, x: 2 }}
                              whileTap={{ scale: 0.98 }}
                              onClick={() => window.location.href = action.path}
                              style={{
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'space-between',
                                padding: '8px 12px',
                                borderRadius: '8px',
                                background: 'rgba(0,212,255,0.06)',
                                border: '1px solid rgba(0,212,255,0.1)',
                                color: '#00D4FF',
                                fontSize: '11px',
                                fontWeight: 600,
                                cursor: 'pointer',
                                transition: 'all 120ms',
                                textAlign: 'left',
                              }}
                            >
                              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                                {action.label.includes('Map') || action.label.includes('Dashboard') ? <MapPin size={12} /> : action.label.includes('Simulation') ? <Activity size={12} /> : <Target size={12} />}
                                <span>{action.label}</span>
                              </div>
                              <ArrowRight size={12} style={{ opacity: 0.6 }} />
                            </motion.button>
                          ))}
                        </div>
                      )}

                      {/* Timestamp */}
                      <div style={{
                        fontSize: '9px',
                        color: msg.role === 'user' ? 'rgba(255,255,255,0.25)' : 'rgba(255,255,255,0.15)',
                        marginTop: '6px',
                        textAlign: msg.role === 'user' ? 'right' : 'left',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px',
                        justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start',
                      }}>
                        <Clock size={8} />
                        {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>

              {isLoading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  style={{ display: 'flex', gap: '10px', alignItems: 'center' }}
                >
                  <div style={{
                    width: '30px',
                    height: '30px',
                    borderRadius: '10px',
                    background: `${agent.color}15`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    border: `1px solid ${agent.color}20`,
                    fontSize: '16px',
                  }}>
                    {agent.icon}
                  </div>
                  <div style={{
                    padding: '12px 16px',
                    background: 'rgba(255,255,255,0.03)',
                    borderRadius: '14px',
                    border: '1px solid rgba(255,255,255,0.06)',
                    backdropFilter: 'blur(8px)',
                  }}>
                    <div style={{ display: 'flex', gap: '5px', alignItems: 'center' }}>
                      {[0, 1, 2].map(i => (
                        <motion.div
                          key={i}
                          animate={{ y: [0, -5, 0] }}
                          transition={{ duration: 0.6, repeat: Infinity, delay: i * 0.15, ease: 'easeInOut' }}
                          style={{
                            width: '6px',
                            height: '6px',
                            borderRadius: '50%',
                            background: agent.color,
                            opacity: 0.7,
                          }}
                        />
                      ))}
                      <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.3)', marginLeft: '4px' }}>Analyzing...</span>
                    </div>
                  </div>
                </motion.div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <div style={{ padding: '12px 14px', borderTop: '1px solid rgba(255,255,255,0.06)', background: 'rgba(0,0,0,0.15)' }}>
              <div style={{ display: 'flex', gap: '8px' }}>
                <textarea
                  value={input}
                  onChange={e => setInput(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) handleSend(); }}
                  placeholder={`Ask ${agent.name.split(' ')[0]} about ${agent.domain.split('·')[0].trim().toLowerCase()}...`}
                  rows={2}
                  style={{
                    flex: 1,
                    background: 'rgba(0,0,0,0.25)',
                    border: '1px solid rgba(255,255,255,0.08)',
                    borderRadius: '10px',
                    padding: '10px 14px',
                    color: 'rgba(255,255,255,0.85)',
                    fontSize: '13px',
                    resize: 'none',
                    outline: 'none',
                    fontFamily: 'inherit',
                  }}
                />
                <motion.button
                  whileHover={input.trim() && !isLoading ? { scale: 1.04 } : {}}
                  whileTap={input.trim() && !isLoading ? { scale: 0.96 } : {}}
                  onClick={handleSend}
                  disabled={!input.trim() || isLoading}
                  style={{
                    padding: '10px 14px',
                    background: !input.trim() || isLoading ? 'rgba(255,255,255,0.06)' : 'linear-gradient(135deg, #00D4FF, #7C3AED)',
                    border: 'none',
                    borderRadius: '10px',
                    color: '#FFFFFF',
                    fontWeight: 700,
                    fontSize: '13px',
                    cursor: input.trim() && !isLoading ? 'pointer' : 'not-allowed',
                    opacity: input.trim() && !isLoading ? 1 : 0.3,
                    alignSelf: 'flex-end',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px',
                  }}
                >
                  <Send size={14} />
                  Send
                </motion.button>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '4px' }}>
                <button
                  onClick={() => { clearConversation(agentId); }}
                  style={{ fontSize: '10px', color: 'rgba(255,255,255,0.2)', background: 'none', border: 'none', cursor: 'pointer', padding: '2px 4px', borderRadius: '4px' }}
                >
                  Clear chat
                </button>
                <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.2)' }}>
                  Ctrl+Enter to send · {agent.name}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
