"use client";

import React, { useState, useEffect } from 'react';
import {
  useAgentStore, useUIStore, useCityDataStore, useSimulationStore,
  AGENTS, AgentId, AgentMessage,
} from '@/stores';

// Deterministic responses per agent
const AGENT_RESPONSES: Record<AgentId, Record<string, string>> = {
  executive: {
    default: "Based on current city metrics — City Health 64/100, Congestion 67%, AQI 142 — I recommend three immediate priorities:\n\n**1. Metro Corridor Acceleration** — Electronic City to Hebbal line has the highest ROI based on traffic density modeling. Impact: −12% congestion on Outer Ring Road.\n\n**2. Eastern Substation Reinforcement** — Substations #7 and #11 are at 91% and 87% capacity. Risk of cascading failure by Q3 2027 if not addressed.\n\n**3. Water Infrastructure NE Corridor** — Demand-supply gap of 350 MLD projected by 2027 in Whitefield-Marathahalli belt.\n\nShall I generate a board-ready briefing on any of these?",
    briefing: "**BENGALURU URBAN INTELLIGENCE — QUARTERLY BRIEFING**\n\nCity Health Score: **64/100** (Moderate)\n\nKey Findings:\n• Traffic congestion at 67% — up 4% vs Q3\n• AQI at 142 — Moderate category, improving\n• Grid load at 4.1 GW — stable, headroom adequate\n• Water stress index: 1.24 — above sustainable threshold\n\nRecommended Actions:\n1. Expedite Metro Line 4 tender (saves ₹340 Cr in road maintenance)\n2. Approve 50 EV charging stations in Electronic City\n3. Emergency water audit — Bellandur catchment zone\n\n*Generated by Bhavora Urban Intelligence OS — confidence 87%*",
  },
  urban: {
    default: "For metro corridor optimization, the Hebbal–Whitefield alignment shows the highest population-weighted demand. Based on gravity model analysis:\n\n**Priority Corridors:**\n1. Hebbal → Whitefield (demand: 285k pax/day)\n2. Sarjapur Road extension (demand: 198k pax/day)\n3. Outer Ring Road phase 3 (demand: 176k pax/day)\n\nHigh-density residential development is most viable in:\n- Sarjapur Road (FSI 4.0 permissible)\n- Thanisandra Main Road (transit-oriented zone)\n- Yelahanka New Town (metro station proximity)\n\nShould I run a full zoning analysis for any of these areas?",
    density: "Whitefield faces a density problem: 18,000 persons/km² with inadequate trunk infrastructure. Recommended interventions:\n\n**Immediate:** \n• Enforce parking caps to discourage private vehicle use\n• Prioritize BMTC feeder routes to existing metro at Kadugodi\n\n**Medium-term:**\n• Widen Hope Farm Junction — single point causing 34% area congestion\n• Commercial-residential mixed-use permitted along 150m of Whitefield Main Road\n\n**Long-term:**\n• Phase 2 purple line extension adds 4 new stations in zone\n• Expected impact: −22% peak congestion, +18% property value",
  },
  disaster: {
    default: "Monsoon flood risk analysis for Bengaluru 2025:\n\n**High Risk Zones (100-year flood):**\n🔴 Bellandur Lake periphery — 3,200 households at risk\n🔴 Varthur catchment — 1,800 structures in flood plain\n🔴 Koramangala valley — Storm drain capacity exceeded at >85mm/hr\n\n**Medium Risk:**\n🟡 Hebbal valley — overflow risk above 95mm/24hr\n🟡 Rachenahalli Lake area — bund maintenance overdue\n\n**Recommended pre-monsoon actions:**\n1. Desilting — 23 storm drains require emergency desilting\n2. Pump station readiness audit — 8 stations not operational\n3. Early warning sensors — install 12 sensors in high-risk zones\n\nShall I generate an evacuation plan for any specific zone?",
    evacuation: "**EVACUATION PLAN — ELECTRONIC CITY**\n\nTrigger: Grid failure or flash flood event\n\nPrimary Routes:\n→ Electronic City Phase 1: Hosur Road to NICE Road (capacity 18,000 veh/hr)\n→ Electronic City Phase 2: Neeladri Road to Bommasandra (capacity 12,000 veh/hr)\n\nAssembly Points:\n• Bommasandra Ground — capacity 8,000 persons\n• Hebbagodi School — capacity 3,500 persons\n\nTimeline:\n• T+0: Alert activated\n• T+15min: Traffic police deployed at 6 junctions\n• T+30min: BMTC emergency buses dispatched (14 buses)\n• T+2hr: Target 80% evacuation complete\n\nEstimated affected population: 47,000 in Zone 4",
  },
  sustainability: {
    default: "Carbon neutrality pathway for Bengaluru by 2040:\n\n**Current State:** 42,000 kt CO₂/yr\n**2040 Target:** Net Zero\n\n**Pathway:**\n2025-2028: EV fleet transition (−8% transport CO₂)\n2028-2032: 60% renewable grid (−18% energy CO₂)\n2032-2036: Green building codes (−6% building CO₂)\n2036-2040: Industrial efficiency + carbon sequestration\n\n**Key Lever — Carbon by Sector:**\n• Transport: 43% → target 15% by 2040 (EV + Metro)\n• Energy: 39% → target 5% (renewables)\n• Industry: 18% → target 8% (efficiency standards)\n\nWater stress outlook: 1.24 → projected 1.68 by 2030 without intervention. Priority: upgrade Cauvery Stage 5 supply.",
    water: "Water stress forecast for Bengaluru 2025-2030:\n\n**Current:** Demand 1,800 MLD | Supply 1,450 MLD | Gap: 350 MLD\n\n**2027 Projection:**\n• Demand: 2,050 MLD (+14%)\n• Supply: 1,580 MLD (Stage 5 upgrade)\n• Gap: **470 MLD** (critical)\n\n**District Risk Map:**\n🔴 Whitefield: 62% groundwater dependent, depletion rate 3m/yr\n🔴 Electronic City: 78% tanker dependent during peak\n🟡 Koramangala: Aging network, 40% distribution loss\n🟢 Indiranagar: Cauvery supply reliable\n\n**Priority Actions:**\n1. Accelerate Cauvery Stage 5 (adds 775 MLD by 2026)\n2. 150 rainwater harvesting mandatory structures in Whitefield\n3. 40% distribution loss reduction program (saves 300 MLD/yr)",
  },
  infrastructure: {
    default: "Power grid risk assessment — Bengaluru 2025:\n\n**Substations at Risk:**\n🔴 Substation #7 (Whitefield) — 91% capacity, maintenance overdue 8 months\n🔴 Substation #11 (Electronic City) — 87% capacity, aging transformers\n🟡 Substation #23 (Hebbal) — 74% capacity, growth trajectory concerning\n🟡 Substation #31 (Sarjapur) — 71% capacity, new residential adds load\n\n**Recommended EV Station Locations (next 50):**\nTop priority: Whitefield, Koramangala, Indiranagar (high EV adoption + low density coverage)\nSecondary: Hebbal, Jayanagar, JP Nagar\n\n**Maintenance Priority Order:**\n1. Sub #7 — emergency transformer replacement (Q2 2025)\n2. Sub #11 — load balancing + new feeder (Q3 2025)\n3. Road network: Outer Ring Road 4-lane → 6-lane from Marathahalli to KR Puram",
    ev: "**EV Charging Station Placement Analysis**\n\nOptimal 50 locations based on:\n• Population density\n• Vehicle registration data\n• Existing coverage gaps\n• Grid capacity availability\n\n**Zone A — Whitefield (12 stations)**\nHope Farm Junction × 3, Whitefield Main Road × 4, ITPL × 3, VGP Garden × 2\nGrid feeder: Whitefield 66kV substation (available capacity: 8 MW)\n\n**Zone B — Electronic City (10 stations)**\nPhase 1 × 5, Phase 2 × 3, Bommasandra × 2\nGrid feeder: Hebbagodi 66kV (available: 6.5 MW)\n\n**Zone C — Koramangala (8 stations)**\n1st–8th Block distribution, Sony World signal area\n\nTotal estimated cost: ₹24 Cr\nPayback period: 6.2 years at current utilization rates",
  },
};

function getAgentResponse(agentId: AgentId, userMessage: string): string {
  const lowerMsg = userMessage.toLowerCase();
  const responses = AGENT_RESPONSES[agentId];

  if (agentId === 'executive') {
    if (lowerMsg.includes('brief') || lowerMsg.includes('summary') || lowerMsg.includes('report')) return responses.briefing;
    return responses.default;
  }
  if (agentId === 'urban') {
    if (lowerMsg.includes('density') || lowerMsg.includes('whitefield')) return responses.density;
    return responses.default;
  }
  if (agentId === 'disaster') {
    if (lowerMsg.includes('evacuat') || lowerMsg.includes('electronic city')) return responses.evacuation;
    return responses.default;
  }
  if (agentId === 'sustainability') {
    if (lowerMsg.includes('water') || lowerMsg.includes('stress')) return responses.water;
    return responses.default;
  }
  if (agentId === 'infrastructure') {
    if (lowerMsg.includes('ev') || lowerMsg.includes('charging')) return responses.ev;
    return responses.default;
  }
  return responses.default;
}

// Format markdown-ish responses
function FormatResponse({ text }: { text: string }) {
  const lines = text.split('\n');
  return (
    <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.8)', lineHeight: 1.7 }}>
      {lines.map((line, i) => {
        if (line.startsWith('**') && line.endsWith('**')) {
          return <div key={i} style={{ fontWeight: 700, color: '#fff', marginTop: i > 0 ? '12px' : 0, marginBottom: '4px' }}>{line.replace(/\*\*/g, '')}</div>;
        }
        if (line.startsWith('• ') || line.startsWith('→ ')) {
          return <div key={i} style={{ paddingLeft: '12px', color: 'rgba(255,255,255,0.7)' }}>{line}</div>;
        }
        if (line.match(/^\d\./)) {
          return <div key={i} style={{ paddingLeft: '12px', color: 'rgba(255,255,255,0.7)' }}>{line}</div>;
        }
        if (line.includes('🔴') || line.includes('🟡') || line.includes('🟢')) {
          return <div key={i} style={{ paddingLeft: '8px' }}>{line}</div>;
        }
        if (line.startsWith('*') && line.endsWith('*')) {
          return <div key={i} style={{ fontSize: '11px', color: 'rgba(255,255,255,0.35)', fontStyle: 'italic', marginTop: '8px' }}>{line.replace(/\*/g, '')}</div>;
        }
        if (line === '') return <div key={i} style={{ height: '6px' }} />;
        return <div key={i}>{line}</div>;
      })}
    </div>
  );
}

export function AgentHub() {
  const { isAgentHubOpen, activeAgentId, openAgentHub, closeAgentHub } = useUIStore();
  const { conversations, addMessage, clearConversation, isLoading, setLoading } = useAgentStore();
  const cityData = useCityDataStore();
  const sim = useSimulationStore();

  const [input, setInput] = useState('');
  const messagesEndRef = React.useRef<HTMLDivElement>(null);

  const agentId = activeAgentId as AgentId;
  const agent = AGENTS[agentId];
  const messages = conversations[agentId] || [];

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;
    const userMsg: AgentMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content: input.trim(),
      timestamp: new Date(),
    };
    addMessage(agentId, userMsg);
    setInput('');
    setLoading(true);

    // Simulate API delay
    await new Promise(r => setTimeout(r, 1200 + Math.random() * 800));

    const responseText = getAgentResponse(agentId, userMsg.content);
    const agentMsg: AgentMessage = {
      id: `msg-${Date.now() + 1}`,
      role: 'agent',
      content: responseText,
      timestamp: new Date(),
    };
    addMessage(agentId, agentMsg);
    setLoading(false);
  };

  return (
    <>
      {/* FAB */}
      <button
        onClick={() => isAgentHubOpen ? closeAgentHub() : openAgentHub()}
        style={{
          position: 'fixed',
          bottom: '24px',
          right: '24px',
          width: '56px',
          height: '56px',
          borderRadius: '50%',
          background: 'linear-gradient(135deg, #00D4FF, #7C3AED)',
          border: 'none',
          cursor: 'pointer',
          zIndex: 9990,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: '22px',
          boxShadow: '0 4px 24px rgba(0,212,255,0.35), 0 8px 40px rgba(124,58,237,0.2)',
          transition: 'all 150ms ease',
          transform: isAgentHubOpen ? 'scale(0.9)' : 'scale(1)',
        }}
        title="AI Agent Hub (Ctrl+/)"
        aria-label="Open AI Agent Hub"
      >
        🤖
      </button>

      {/* Panel */}
      {isAgentHubOpen && (
        <div
          style={{
            position: 'fixed',
            right: '24px',
            bottom: '96px',
            width: '420px',
            maxHeight: '75vh',
            background: '#0A1628',
            border: '1px solid rgba(0,212,255,0.12)',
            borderRadius: '16px',
            boxShadow: '0 24px 80px rgba(0,0,0,0.6), 0 0 0 1px rgba(0,212,255,0.05)',
            zIndex: 9989,
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
            animation: 'scale-in 0.18s ease-out',
          }}
        >
          {/* Header */}
          <div style={{
            padding: '12px 16px',
            borderBottom: '1px solid rgba(255,255,255,0.06)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span style={{ fontSize: '18px' }}>🤖</span>
              <div>
                <div style={{ fontSize: '13px', fontWeight: 700, color: '#fff' }}>Urban Copilot</div>
                <div style={{ fontSize: '10px', color: '#00D4FF', textTransform: 'uppercase', letterSpacing: '0.08em' }}>AI Agents</div>
              </div>
            </div>
            <button onClick={closeAgentHub} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '18px' }}>×</button>
          </div>

          {/* Agent Selector */}
          <div style={{
            display: 'flex',
            gap: '4px',
            padding: '10px 12px',
            borderBottom: '1px solid rgba(255,255,255,0.06)',
            overflowX: 'auto',
          }}>
            {(Object.values(AGENTS) as typeof AGENTS[AgentId][]).map(a => (
              <button
                key={a.id}
                onClick={() => openAgentHub(a.id)}
                style={{
                  padding: '6px 10px',
                  borderRadius: '20px',
                  border: `1px solid ${activeAgentId === a.id ? a.color : 'rgba(255,255,255,0.08)'}`,
                  background: activeAgentId === a.id ? `${a.color}18` : 'transparent',
                  color: activeAgentId === a.id ? a.color : 'rgba(255,255,255,0.5)',
                  fontSize: '11px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  whiteSpace: 'nowrap',
                  transition: 'all 120ms',
                }}
              >
                {a.icon} {a.name.split(' ')[0]}
              </button>
            ))}
          </div>

          {/* Context Strip */}
          <div style={{
            padding: '8px 14px',
            background: 'rgba(255,255,255,0.02)',
            borderBottom: '1px solid rgba(255,255,255,0.04)',
            display: 'flex',
            gap: '12px',
            flexWrap: 'wrap',
          }}>
            <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.35)', fontFamily: 'var(--font-jetbrains, monospace)' }}>
              AQI {cityData.metrics.aqi} · Traffic {cityData.metrics.congestionIndex}% · Incidents {cityData.metrics.activeIncidents}
            </span>
          </div>

          {/* Quick Actions */}
          <div style={{ padding: '8px 12px', display: 'flex', gap: '6px', flexWrap: 'wrap', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
            {agent.quickActions.slice(0, 4).map(action => (
              <button
                key={action}
                onClick={() => setInput(action)}
                style={{
                  padding: '4px 8px',
                  borderRadius: '4px',
                  background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(255,255,255,0.08)',
                  color: 'rgba(255,255,255,0.6)',
                  fontSize: '11px',
                  cursor: 'pointer',
                  transition: 'all 120ms',
                }}
                className="hover:text-white hover:border-[rgba(0,212,255,0.3)]"
              >
                {action}
              </button>
            ))}
          </div>

          {/* Messages */}
          <div style={{ flex: 1, overflowY: 'auto', padding: '12px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {messages.length === 0 && (
              <div style={{ textAlign: 'center', padding: '24px', color: 'rgba(255,255,255,0.3)', fontSize: '12px' }}>
                <div style={{ fontSize: '24px', marginBottom: '8px' }}>{agent.icon}</div>
                <div style={{ fontWeight: 600, color: 'rgba(255,255,255,0.5)', marginBottom: '4px' }}>{agent.name}</div>
                <div>{agent.domain}</div>
                <div style={{ marginTop: '8px' }}>Ask me anything about {agent.domain.split('·')[0].trim().toLowerCase()}</div>
              </div>
            )}
            {messages.map(msg => (
              <div
                key={msg.id}
                style={{
                  display: 'flex',
                  flexDirection: msg.role === 'user' ? 'row-reverse' : 'row',
                  gap: '8px',
                  alignItems: 'flex-start',
                }}
              >
                {msg.role === 'agent' && (
                  <span style={{ fontSize: '20px', flexShrink: 0 }}>{agent.icon}</span>
                )}
                <div style={{
                  maxWidth: '80%',
                  padding: '10px 12px',
                  borderRadius: msg.role === 'user' ? '12px 12px 4px 12px' : '12px 12px 12px 4px',
                  background: msg.role === 'user' ? 'rgba(0,212,255,0.1)' : '#0F1E38',
                  border: `1px solid ${msg.role === 'user' ? 'rgba(0,212,255,0.15)' : 'rgba(255,255,255,0.06)'}`,
                }}>
                  {msg.role === 'agent' ? (
                    <FormatResponse text={msg.content} />
                  ) : (
                    <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.9)' }}>{msg.content}</div>
                  )}
                </div>
              </div>
            ))}
            {isLoading && (
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <span style={{ fontSize: '20px' }}>{agent.icon}</span>
                <div style={{ padding: '10px 14px', background: '#0F1E38', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.06)' }}>
                  <div style={{ display: 'flex', gap: '4px' }}>
                    {[0, 1, 2].map(i => (
                      <div key={i} style={{
                        width: '6px', height: '6px', borderRadius: '50%',
                        background: '#00D4FF', opacity: 0.6,
                        animation: `fade-in 0.6s ease-in-out ${i * 0.2}s infinite alternate`,
                      }} />
                    ))}
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Input */}
          <div style={{ padding: '12px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
            <div style={{ display: 'flex', gap: '8px' }}>
              <textarea
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) handleSend(); }}
                placeholder={`Ask ${agent.name.split(' ')[0]} about ${agent.domain.split('·')[0].trim().toLowerCase()}...`}
                rows={2}
                style={{
                  flex: 1,
                  background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(255,255,255,0.08)',
                  borderRadius: '8px',
                  padding: '8px 12px',
                  color: '#fff',
                  fontSize: '13px',
                  resize: 'none',
                  outline: 'none',
                  fontFamily: 'inherit',
                }}
              />
              <button
                onClick={handleSend}
                disabled={!input.trim() || isLoading}
                style={{
                  padding: '8px 14px',
                  background: 'linear-gradient(135deg, #00D4FF, #0099CC)',
                  border: 'none',
                  borderRadius: '8px',
                  color: '#050A14',
                  fontWeight: 700,
                  fontSize: '13px',
                  cursor: input.trim() && !isLoading ? 'pointer' : 'not-allowed',
                  opacity: input.trim() && !isLoading ? 1 : 0.4,
                  alignSelf: 'flex-end',
                }}
              >
                Send
              </button>
            </div>
            <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.2)', marginTop: '4px', textAlign: 'right' }}>
              Ctrl+Enter to send · {agent.name}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
